// src/routes/(app)/(protected)/tickets/+page.svelte
<script lang="ts">
  import { useQuery } from "convex-svelte";
  import { api } from "@/convex/_generated/api";
  import { getChainLabel } from "@/lib/chains";
  import ConnectWallet from "$lib/components/ConnectWallet.svelte";
  import TicketQRCode from "$lib/components/TicketQRCode.svelte";
  import Badge from "$lib/components/ui/Badge.svelte";
  import Button from "$lib/components/ui/Button.svelte";
  import Card from "$lib/components/ui/Card.svelte";
  import CardContent from "$lib/components/ui/CardContent.svelte";
  import CardHeader from "$lib/components/ui/CardHeader.svelte";
  import CardTitle from "$lib/components/ui/CardTitle.svelte";
  import { getClerkContext } from "$lib/stores/clerk.svelte";

  const clerkContext = getClerkContext();
  const isSignedIn = $derived(Boolean(clerkContext.currentSession));

  const ticketsQuery = useQuery(api.tickets.listMine, () => (isSignedIn ? {} : "skip"));
  const eventIds = $derived(
    Array.from(new Set((ticketsQuery.data ?? []).map((ticket) => ticket.eventId))),
  );
  const eventsQuery = useQuery(api.events.getMany, () =>
    eventIds.length > 0 ? { ids: eventIds } : "skip",
  );
  const activeQrTokensQuery = useQuery(api.qr.listActiveByTickets, () =>
    ticketsQuery.data && ticketsQuery.data.length > 0
      ? { ticketIds: ticketsQuery.data.map((ticket) => ticket._id) }
      : "skip",
  );

  const eventsById = $derived(
    new Map((eventsQuery.data ?? []).map((event) => [event._id, event])),
  );
  const activeQrByTicketId = $derived(
    new Map((activeQrTokensQuery.data ?? []).map((qr) => [qr.ticketId, qr])),
  );

  function getTicketBadgeVariant(status: "active" | "listed" | "transferred" | "refunded") {
    switch (status) {
      case "active":
        return "default";
      case "listed":
        return "secondary";
      default:
        return "outline";
    }
  }
</script>

<main class="container mx-auto px-4 py-8">
  <h1 class="mb-2 text-3xl font-black uppercase tracking-wide">My Tickets</h1>
  <p class="mb-8 text-sm text-muted-foreground">
    Your purchased event tickets across Monad Testnet and Base Mainnet
  </p>

  {#if !isSignedIn}
    <div class="space-y-4 border-2 border-dashed border-foreground/30 py-24 text-center">
      <p class="text-muted-foreground">Sign in to see your tickets</p>
      <ConnectWallet />
    </div>
  {:else if ticketsQuery.isLoading || ticketsQuery.data === undefined}
    <div class="border-2 border-dashed border-foreground/30 py-24 text-center text-muted-foreground">
      Loading tickets...
    </div>
  {:else if ticketsQuery.data.length === 0}
    <div class="border-2 border-dashed border-foreground/30 py-24 text-center">
      <p class="mb-4 text-muted-foreground">No tickets yet.</p>
      <Button href="/events">Browse Events</Button>
    </div>
  {:else}
    <div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
      {#each ticketsQuery.data as ticket (ticket._id)}
        {@const event = eventsById.get(ticket.eventId)}
        {@const activeQrToken = activeQrByTicketId.get(ticket._id)?.token}
        {@const qrValue = activeQrToken ?? ticket.qrCode}
        <Card>
          <CardHeader>
            <div class="flex items-start justify-between">
              <CardTitle class="text-base">{event?.name ?? "Loading..."}</CardTitle>
              <div class="flex items-center gap-2">
                <Badge variant="outline">{getChainLabel(ticket.chainKey)}</Badge>
                <Badge variant={getTicketBadgeVariant(ticket.status)}>{ticket.status}</Badge>
              </div>
            </div>
          </CardHeader>
          <CardContent class="space-y-3 text-sm">
            {#if event}
              <div class="flex justify-between">
                <span class="text-xs uppercase tracking-wider text-muted-foreground">Event Date</span>
                <span class="font-mono">{new Date(event.startTime).toLocaleDateString()}</span>
              </div>
            {/if}
            <div class="flex justify-between">
              <span class="text-xs uppercase tracking-wider text-muted-foreground">Paid</span>
              <span class="font-mono font-bold">
                {ticket.purchasePrice === 0 ? "Free" : `$${ticket.purchasePrice} USDC`}
              </span>
            </div>
            {#if ticket.tokenId !== undefined}
              <div class="flex justify-between">
                <span class="text-xs uppercase tracking-wider text-muted-foreground">Token ID</span>
                <span class="font-mono">#{ticket.tokenId}</span>
              </div>
            {/if}
            <div class="flex justify-between">
              <span class="text-xs uppercase tracking-wider text-muted-foreground">Tx</span>
              <span class="ml-2 truncate font-mono text-xs">{ticket.txHash.slice(0, 10)}...</span>
            </div>
            <div class="flex justify-between">
              <span class="text-xs uppercase tracking-wider text-muted-foreground">Entry</span>
              <span class={`font-bold ${ticket.checkedInAt ? "text-accent" : "text-primary"}`}>
                {ticket.checkedInAt ? "Used" : "Not used"}
              </span>
            </div>
            {#if ticket.checkedInAt}
              <div class="flex justify-between">
                <span class="text-xs uppercase tracking-wider text-muted-foreground">Checked In</span>
                <span class="font-mono text-xs">{new Date(ticket.checkedInAt).toLocaleString()}</span>
              </div>
            {/if}
            <div class="space-y-2 pt-1">
              <p class="text-xs uppercase tracking-wider text-muted-foreground">Ticket QR</p>
              <div class="flex justify-center">
                <TicketQRCode value={qrValue} />
              </div>
              <p class="break-all font-mono text-[10px] text-muted-foreground">{qrValue}</p>
            </div>

            {#if ticket.status === "active" && event}
              <Button class="mt-2 w-full" href={`/events/${event._id}`} size="sm" variant="outline">
                View Event
              </Button>
            {/if}
          </CardContent>
        </Card>
      {/each}
    </div>
  {/if}
</main>

// app/tickets/page.tsx
/// app/tickets/page.tsx — My tickets page
"use client";

import { useMemo, useSyncExternalStore } from "react";
import Link from "next/link";
import { useQuery } from "convex/react";
import { useUser } from "@clerk/nextjs";
import { api } from "../../convex/_generated/api";
import type { Doc, Id } from "../../convex/_generated/dataModel";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ConnectWallet } from "@/components/ConnectWallet";
import { TicketQRCode } from "@/components/TicketQRCode";
import { Header } from "@/components/Header";
import { getChainLabel } from "@/lib/chains";

type Ticket = {
  _id: Id<"tickets">;
  eventId: Id<"events">;
  tokenId?: number;
  buyerAddress: string;
  purchasePrice: number;
  txHash: string;
  qrCode: string;
  chainKey: "monadTestnet" | "baseMainnet";
  checkedInAt?: number;
  checkedInBy?: string;
  status: "active" | "listed" | "transferred" | "refunded";
};

const emptySubscribe = () => () => {};

export default function TicketsPage() {
  const { isLoaded, isSignedIn } = useUser();
  const isHydrated = useSyncExternalStore(
    emptySubscribe,
    () => true,
    () => false,
  );
  const isSessionReady = isHydrated && isLoaded;
  const tickets = useQuery(api.tickets.listMine, isSessionReady && isSignedIn ? {} : "skip");
  const eventIds = useMemo(
    () =>
      tickets
        ? Array.from(new Set(tickets.map((ticket) => ticket.eventId)))
        : [],
    [tickets],
  );
  const events = useQuery(
    api.events.getMany,
    eventIds.length > 0 ? { ids: eventIds } : "skip",
  );
  const activeQrTokens = useQuery(
    api.qr.listActiveByTickets,
    tickets && tickets.length > 0
      ? { ticketIds: tickets.map((ticket) => ticket._id) }
      : "skip",
  );
  const eventsById = useMemo(
    () => new Map((events ?? []).map((event) => [event._id, event])),
    [events],
  );
  const activeQrByTicketId = useMemo(
    () =>
      new Map(
        (activeQrTokens ?? []).map((qr) => [qr.ticketId, qr]),
      ),
    [activeQrTokens],
  );

  return (
    <div className="min-h-screen bg-background">
      <Header />

      <main className="container mx-auto px-4 py-8">
        <h1 className="text-3xl font-black uppercase tracking-wide mb-2">My Tickets</h1>
        <p className="text-muted-foreground mb-8 text-sm">
          Your purchased event tickets across Monad Testnet and Base Mainnet
        </p>

        {!isSessionReady ? (
          <div className="text-center py-24 text-muted-foreground border-2 border-dashed border-foreground/30">
            Loading session...
          </div>
        ) : !isSignedIn ? (
          <div className="text-center py-24 space-y-4 border-2 border-dashed border-foreground/30">
            <p className="text-muted-foreground">Sign in to see your tickets</p>
            <ConnectWallet />
          </div>
        ) : tickets === undefined ? (
          <div className="text-center py-24 text-muted-foreground border-2 border-dashed border-foreground/30">
            Loading tickets...
          </div>
        ) : tickets.length === 0 ? (
          <div className="text-center py-24 border-2 border-dashed border-foreground/30">
            <p className="text-muted-foreground mb-4">No tickets yet.</p>
            <Link href="/events">
              <Button>Browse Events</Button>
            </Link>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {tickets.map((ticket) => (
              <TicketCard
                key={ticket._id}
                ticket={ticket}
                event={eventsById.get(ticket.eventId)}
                activeQrToken={activeQrByTicketId.get(ticket._id)?.token}
              />
            ))}
          </div>
        )}
      </main>
    </div>
  );
}

function getTicketBadgeVariant(status: Ticket["status"]) {
  switch (status) {
    case "active":
      return "default";
    case "listed":
      return "secondary";
    default:
      return "outline";
  }
}

function TicketCard({
  ticket,
  event,
  activeQrToken,
}: {
  ticket: Ticket;
  event: Doc<"events"> | undefined;
  activeQrToken?: string;
}) {
  const qrValue = activeQrToken ?? ticket.qrCode;

  return (
    <Card>
      <CardHeader>
        <div className="flex justify-between items-start">
          <CardTitle className="text-base">
            {event?.name ?? "Loading..."}
          </CardTitle>
          <div className="flex items-center gap-2">
            <Badge variant="outline">{getChainLabel(ticket.chainKey)}</Badge>
            <Badge variant={getTicketBadgeVariant(ticket.status)}>
              {ticket.status}
            </Badge>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-3 text-sm">
        {event && (
          <div className="flex justify-between">
            <span className="text-muted-foreground uppercase text-xs tracking-wider">Event Date</span>
            <span className="font-mono">{new Date(event.startTime).toLocaleDateString()}</span>
          </div>
        )}
        <div className="flex justify-between">
          <span className="text-muted-foreground uppercase text-xs tracking-wider">Paid</span>
          <span className="font-mono font-bold">
            {ticket.purchasePrice === 0
              ? "Free"
              : `$${ticket.purchasePrice} USDC`}
          </span>
        </div>
        {ticket.tokenId !== undefined && (
          <div className="flex justify-between">
            <span className="text-muted-foreground uppercase text-xs tracking-wider">Token ID</span>
            <span className="font-mono">#{ticket.tokenId}</span>
          </div>
        )}
        <div className="flex justify-between">
          <span className="text-muted-foreground uppercase text-xs tracking-wider">Tx</span>
          <span className="font-mono text-xs truncate ml-2">
            {ticket.txHash.slice(0, 10)}...
          </span>
        </div>
        <div className="flex justify-between">
          <span className="text-muted-foreground uppercase text-xs tracking-wider">Entry</span>
          <span className={`font-bold ${ticket.checkedInAt ? "text-accent" : "text-primary"}`}>
            {ticket.checkedInAt ? "Used" : "Not used"}
          </span>
        </div>
        {ticket.checkedInAt && (
          <div className="flex justify-between">
            <span className="text-muted-foreground uppercase text-xs tracking-wider">Checked In</span>
            <span className="text-xs font-mono">{new Date(ticket.checkedInAt).toLocaleString()}</span>
          </div>
        )}
        <div className="space-y-2 pt-1">
          <p className="text-muted-foreground text-xs uppercase tracking-wider">Ticket QR</p>
          <div className="flex justify-center">
            <TicketQRCode value={qrValue} />
          </div>
          <p className="font-mono text-[10px] break-all text-muted-foreground">
            {qrValue}
          </p>
        </div>

        {ticket.status === "active" && event && (
          <Link href={`/events/${event._id}`}>
            <Button variant="outline" size="sm" className="w-full mt-2">
              View Event
            </Button>
          </Link>
        )}
      </CardContent>
    </Card>
  );
}
