// src/lib/components/Header.svelte
<script lang="ts">
  import { resolve } from "$app/paths";
  import Badge from "$lib/components/ui/Badge.svelte";
  import Button from "$lib/components/ui/Button.svelte";
  import ConnectWallet from "$lib/components/ConnectWallet.svelte";
  import MonadFaucetButton from "$lib/components/MonadFaucetButton.svelte";
</script>

<header class="sticky top-0 z-50 border-b-2 border-foreground bg-background">
  <div class="container mx-auto flex h-16 items-center justify-between px-4">
    <a class="flex items-center gap-2" href={resolve("/")}>
      <img alt="BuddyEvents" height="36" src="/logo.svg" width="36" />
      <span class="text-xl font-black uppercase tracking-widest">BuddyEvents</span>
      <div class="hidden items-center gap-1 sm:flex">
        <Badge class="text-[10px]" variant="outline">Monad Testnet</Badge>
        <Badge class="text-[10px]" variant="outline">Base Mainnet</Badge>
      </div>
    </a>
    <nav class="flex items-center gap-2">
      <Button href="/events" size="sm" variant="ghost">Events</Button>
      <Button href="/tickets" size="sm" variant="ghost">My Tickets</Button>
      <Button href="/create" size="sm" variant="ghost">Create</Button>
      <Button href="/check-in" size="sm" variant="ghost">Check-in</Button>
      <MonadFaucetButton />
      <ConnectWallet />
    </nav>
  </div>
</header>

// components/Header.tsx
"use client";

import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ConnectWallet } from "@/components/ConnectWallet";
import { MonadFaucetButton } from "@/components/MonadFaucetButton";

export function Header() {
  return (
    <header className="sticky top-0 z-50 border-b-2 border-foreground bg-background">
      <div className="container mx-auto flex h-16 items-center justify-between px-4">
        <Link href="/" className="flex items-center gap-2">
          <Image src="/logo.svg" alt="BuddyEvents" width={36} height={36} />
          <span className="text-xl font-black uppercase tracking-widest">
            BuddyEvents
          </span>
          <div className="hidden items-center gap-1 sm:flex">
            <Badge variant="outline" className="text-[10px]">
              Monad Testnet
            </Badge>
            <Badge variant="outline" className="text-[10px]">
              Base Mainnet
            </Badge>
          </div>
        </Link>
        <nav className="flex items-center gap-2">
          <Link href="/events">
            <Button variant="ghost" size="sm">Events</Button>
          </Link>
          <Link href="/tickets">
            <Button variant="ghost" size="sm">My Tickets</Button>
          </Link>
          <Link href="/create">
            <Button variant="ghost" size="sm">Create</Button>
          </Link>
          <Link href="/check-in">
            <Button variant="ghost" size="sm">Check-in</Button>
          </Link>
          <MonadFaucetButton />
          <ConnectWallet />
        </nav>
      </div>
    </header>
  );
}
