// src/lib/components/ui/Separator.svelte
<script lang="ts">
  import { cn } from "@/lib/utils";

  let {
    class: className = "",
    orientation = "horizontal",
  }: {
    class?: string;
    orientation?: "horizontal" | "vertical";
  } = $props();
</script>

<div
  class={cn(
    orientation === "horizontal"
      ? "h-[2px] w-full bg-foreground/30"
      : "h-full w-[2px] shrink-0 bg-foreground/30",
    className,
  )}
></div>

// components/ui/separator.tsx
"use client"

import * as React from "react"
import { Separator as SeparatorPrimitive } from "radix-ui"

import { cn } from "@/lib/utils"

function Separator({
  className,
  orientation = "horizontal",
  decorative = true,
  ...props
}: React.ComponentProps<typeof SeparatorPrimitive.Root>) {
  return (
    <SeparatorPrimitive.Root
      data-slot="separator"
      decorative={decorative}
      orientation={orientation}
      className={cn(
        "bg-foreground/30 shrink-0 data-[orientation=horizontal]:h-[2px] data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-[2px]",
        className
      )}
      {...props}
    />
  )
}

export { Separator }
