// app/admin/checkin/page.tsx
"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";

type CheckInResponse = {
  ok: boolean;
  status: "valid" | "invalid" | "expired" | "already_checked_in";
  message: string;
  ticketId?: string;
  eventId?: string;
  checkedInAt?: number;
  error?: string;
};

export default function AdminCheckinPage() {
  const [token, setToken] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<CheckInResponse | null>(null);

  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!token.trim()) return;

    setLoading(true);
    setResult(null);
    try {
      const response = await fetch("/api/checkin/validate", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ token: token.trim() }),
      });

      const payload = (await response.json()) as CheckInResponse;
      setResult(payload);
      if (response.ok && payload.ok) {
        setToken("");
      }
    } catch (error) {
      setResult({
        ok: false,
        status: "invalid",
        message:
          error instanceof Error ? error.message : "Unable to validate token",
      });
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto max-w-2xl px-4 py-8">
        <div className="mb-6 flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-black uppercase tracking-widest">Admin Check-in</h1>
            <p className="text-sm text-muted-foreground">
              Validate QR token payloads and mark tickets as checked-in.
            </p>
          </div>
          <Link href="/admin/events">
            <Button variant="outline">Admin Events</Button>
          </Link>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Scan or Paste QR Token</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <form className="space-y-3" onSubmit={onSubmit}>
              <Input
                value={token}
                onChange={(e) => setToken(e.target.value)}
                placeholder="be_qr_..."
                autoComplete="off"
              />
              <Button type="submit" className="w-full" disabled={loading || !token.trim()}>
                {loading ? "Validating..." : "Validate Check-in"}
              </Button>
            </form>

            {result && (
              <div
                className={`border-2 p-4 text-sm ${
                  result.ok
                    ? "border-primary bg-primary/10"
                    : "border-destructive bg-destructive/10"
                }`}
              >
                <div className="mb-2 flex items-center gap-2">
                  <Badge variant={result.ok ? "default" : "destructive"}>
                    {result.status}
                  </Badge>
                  <span className="font-bold">{result.message}</span>
                </div>
                {result.ticketId && (
                  <p className="font-mono text-xs">Ticket: {result.ticketId}</p>
                )}
                {result.eventId && (
                  <p className="font-mono text-xs">Event: {result.eventId}</p>
                )}
                {result.checkedInAt && (
                  <p className="text-xs font-mono">
                    Checked in at: {new Date(result.checkedInAt).toLocaleString()}
                  </p>
                )}
                {result.error && <p className="text-xs font-mono">{result.error}</p>}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// src/routes/(app)/(protected)/admin/checkin/+page.svelte
<script lang="ts">
  import Badge from "$lib/components/ui/Badge.svelte";
  import Button from "$lib/components/ui/Button.svelte";
  import Card from "$lib/components/ui/Card.svelte";
  import CardContent from "$lib/components/ui/CardContent.svelte";
  import CardHeader from "$lib/components/ui/CardHeader.svelte";
  import CardTitle from "$lib/components/ui/CardTitle.svelte";
  import Input from "$lib/components/ui/Input.svelte";

  type CheckInResponse = {
    ok: boolean;
    status: "valid" | "invalid" | "expired" | "already_checked_in";
    message: string;
    ticketId?: string;
    eventId?: string;
    checkedInAt?: number;
    error?: string;
  };

  let token = $state("");
  let loading = $state(false);
  let result = $state<CheckInResponse | null>(null);

  async function onSubmit(event: SubmitEvent) {
    event.preventDefault();
    if (!token.trim()) return;

    loading = true;
    result = null;
    try {
      const response = await fetch("/api/checkin/validate", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ token: token.trim() }),
      });

      const payload = (await response.json()) as CheckInResponse;
      result = payload;
      if (response.ok && payload.ok) {
        token = "";
      }
    } catch (error) {
      result = {
        ok: false,
        status: "invalid",
        message: error instanceof Error ? error.message : "Unable to validate token",
      };
    } finally {
      loading = false;
    }
  }
</script>

<div class="container mx-auto max-w-2xl px-4 py-8">
  <div class="mb-6 flex items-center justify-between">
    <div>
      <h1 class="text-2xl font-black uppercase tracking-widest">Admin Check-in</h1>
      <p class="text-sm text-muted-foreground">
        Validate QR token payloads and mark tickets as checked-in.
      </p>
    </div>
    <Button href="/admin/events" variant="outline">Admin Events</Button>
  </div>

  <Card>
    <CardHeader>
      <CardTitle>Scan or Paste QR Token</CardTitle>
    </CardHeader>
    <CardContent class="space-y-4">
      <form class="space-y-3" onsubmit={onSubmit}>
        <Input autocomplete="off" bind:value={token} placeholder="be_qr_..." />
        <Button class="w-full" disabled={loading || !token.trim()} type="submit">
          {loading ? "Validating..." : "Validate Check-in"}
        </Button>
      </form>

      {#if result}
        <div
          class={`border-2 p-4 text-sm ${
            result.ok ? "border-primary bg-primary/10" : "border-destructive bg-destructive/10"
          }`}
        >
          <div class="mb-2 flex items-center gap-2">
            <Badge variant={result.ok ? "default" : "destructive"}>{result.status}</Badge>
            <span class="font-bold">{result.message}</span>
          </div>
          {#if result.ticketId}
            <p class="font-mono text-xs">Ticket: {result.ticketId}</p>
          {/if}
          {#if result.eventId}
            <p class="font-mono text-xs">Event: {result.eventId}</p>
          {/if}
          {#if result.checkedInAt}
            <p class="font-mono text-xs">
              Checked in at: {new Date(result.checkedInAt).toLocaleString()}
            </p>
          {/if}
          {#if result.error}
            <p class="font-mono text-xs">{result.error}</p>
          {/if}
        </div>
      {/if}
    </CardContent>
  </Card>
</div>
